spring:
  datasource:
    url: jdbc:mysql://mysql:3306/petclinic
    username: petclinic
    password: petclinic
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
