version: "3.9"

services:
  app-postgres:
    build:
      context: .
      dockerfile: spring-docker.dockerfile
    image: petclinic:latest
    container_name: petclinic_pg
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    depends_on:
      - postgres
    networks: [backend]

  app-mysql:
    build:
      context: .
      dockerfile: spring-docker.dockerfile
    image: petclinic:latest
    container_name: petclinic_mysql
    ports:
      - "8081:8080"   # different port so both can run
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    depends_on:
      - mysql
    networks: [backend]

  postgres:
    image: postgres:15-alpine
    container_name: petclinic_postgres
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [backend]

  mysql:
    image: mysql:8.0
    container_name: petclinic_mysql_db
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: rootpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [backend]

volumes:
  pg_data:
  mysql_data:

networks:
  backend:
    driver: bridge

