management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
# optional: secure actuator endpoints appropriately for prod
