# Global scrape/evaluation defaults that apply (unless overridden per-job)
global:
  scrape_interval: 15s         # how often Prometheus scrapes targets by default
  evaluation_interval: 15s     # how often rules are evaluated (if you have any)

scrape_configs:
  - job_name: 'spring-petclinic'      # logical name for this group of targets
    metrics_path: /actuator/prometheus # where to fetch metrics on each target
    static_configs:
      - targets:
        - 'app-postgres:8080'         # Docker service name + port
        - 'app-mysql:8080'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # self-scrape so Prometheus can monitor itself

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']
